[tool.poetry]
name = "untitledserver-1"
version = "0.1.0"
description = ""
authors = ["ChadFreeman <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
heroku3 = "^4.2.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
